name: Java Tests

on:
  pull_request:

jobs:
  build:
    uses: yandex-praktikum/java-kanban/.github/workflows/api-tests.yml@ci
    steps:
      - name: Run tests
        run: |
          find ./tests -type f -name "*.java" > tests.txt
          javac -d out -cp ./out:./tests/lib/junit-platform-console-standalone-1.9.3.jar:./tests/lib/gson-2.10.1.jar:./tests @tests.txt
